### ISSUE TITLE
HUP does not function properly unless thin is running as a daemon

### ISSUE THREAD

**Issue by SamSaffron** [macournoyer/thin#128]
I noticed that HUP is unable to bind to the socket on restart causing a crash unless thin is executed with -d

**Comment by listrophy** [comment]
+1

This is a problem when running thin from inside of foreman. I've got a lot of processes running in foreman, and sometimes I just want to restart the thin server. Since foreman requires non-daemonized processes, I can't seem to issue a restart to thin without this issue cropping up.
