### ISSUE TITLE
Limit of only 6 concurrent connections open per client?

### ISSUE THREAD

**Issue by iostat** [macournoyer/thin#169]
I'm running Thin 1.5.1 and Sinatra 1.4.2. I'm also using `sinatra_sse` to wrap Sinatra's streaming facilities. I've noticed that, for every machine connecting to my server, each machine can only have 6 open connections at any given time, and Thin will stall any additional connections until one of those six are closed. I am experiencing this issue on both Windows 7 (running Ruby 1.9.3p327) and Mac OS X 10.8.3 (running Ruby 2.0.0p0). Due to the constraints of my application, I cannot have multiple Thin servers running. Additionally, I am not starting my application via Rackup, but rather I am invoking Thin inside an existing EventMachine reactor like so:

``` ruby
EM.run {
  @@thin_instance = Thin::Server.new ip, port, MyApp, signals: false, threaded: true
  @@thin_instance.start
}
```

Any ideas why this could happening? 6 seems like an arbitrary number for a connection limit.

**Comment by contra** [comment]
Just an FYI - the browser has a 6 connection limit per host, so it may not be the server limiting this.

**Comment by iostat** [comment]
@contra: IIRC this was tested with Safari, Firefox, and Chrome, with whatever versions were the latest back then. I guess it's possible all three of those had the same 6 connection limit but it seems a little arbitrary, no?

**Comment by contra** [comment]
@iostat It's a part of the HTTP spec, all browsers have a connection limit. More info: https://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser

Solution is to use HTTP2

**Comment by iostat** [comment]
Never knew that! I guess that explains a lot actually!
