### ISSUE TITLE
Add Upstart support to thin init script

### ISSUE THREAD

**Issue by haad** [macournoyer/thin#197]
_Ubuntu_ now uses upstart. I have spent some time trying to create a correct working init script for upstart.

---

description     "Test App Station"

start on runlevel [2345]
stop on runlevel [!2345]

console log
# expect

respawn
chdir /srv/apps/test_app
setuid innrm

env APP_NAME="test_app"
env HOME="/srv/apps/test_app/current"
env GEM_PATH="/var/lib/ruby-gems/test_app/gems/1.9.1"
env PATH="/sbin:/usr/sbin:/bin:/usr/bin:/var/lib/ruby-gems/test_app/gems/1.9.1/bin"
env BUNDLE_PATH="/var/lib/ruby-gems/test_app/gems/1.9.1/bin/bundle"
env RAILS_ENV="production"
env RAILS_PORT="3000"

pre-start script
   if [ ! -d ${HOME}/tmp/pids ]; then
    mkdir -p ${HOME}/tmp/pids;
   fi
   start-stop-daemon --start -b -d ${HOME} -p ${HOME}/tmp/pids/thin.pid --exec ${BUNDLE_PATH} -m -- exec thin start -e ${RAILS_ENV} -p ${RAILS_PORT} -l $HOME/log/thin.log
   sudo initctl emit ${APP_NAME}_start
end script

post-stop script
  start-stop-daemon --stop -d ${HOME} -p ${HOME}/tmp/pids/thin.pid
  sudo initctl emit ${APP_NAME}_stop

**Comment by hectorcorrea** [comment]
:+1: thanks for posting this. I was having problems with my script and moving the call to `thin start` to the `pre-start script` section as you suggest fixed my problem.
