### ISSUE TITLE
gem install not error handling correctly

### ISSUE THREAD

**Issue by earthgecko** [macournoyer/thin#207]
While testing some functionality of the Redhat Software Collections scl ruby193 packages, I ran into a problem, the problem is with our scl ruby193 env, related to thin_parser.so not being populated to the lib dir

<pre>
[root@ruby193 oculus]# bundle exec thin start
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.5.0/lib/thin.rb:39:in `require': cannot load such file -- thin_parser (LoadError)
from /opt/rh/ruby193/root/usr/share/gems/gems/thin-1.5.0/lib/thin.rb:39:in `<top (required)>'
from /opt/rh/ruby193/root/usr/share/gems/gems/thin-1.5.0/bin/thin:5:in `require'
from /opt/rh/ruby193/root/usr/share/gems/gems/thin-1.5.0/bin/thin:5:in `<top (required)>'
from /opt/rh/ruby193/root/usr/share/gems/bin/thin:23:in `load'
from /opt/rh/ruby193/root/usr/share/gems/bin/thin:23:in `<main>'
[root@ruby193 oculus]#
</pre>

<pre>
[root@ruby193 oculus]# ls -al /opt/rh/ruby193/root/usr/share/gems/gems/thin-1.5.0/lib
total 20
drwxr-xr-x 4 root root 4096 Nov 15 15:31 .
drwxr-xr-x 6 root root 4096 Nov 15 15:31 ..
drwxr-xr-x 3 root root 4096 Nov 15 15:31 rack
drwxr-xr-x 4 root root 4096 Nov 15 15:31 thin
-rw-r--r-- 1 root root 1297 Nov 15 15:31 thin.rb
[root@ruby193 oculus]#
</pre>

This lead down some pathing investigation and some playing with #{Thin::ROOT} patterns, etc

But most certainly it was due to something in our test env.

However it did highlight something, granted something was not correct, but gem install and bundle install reported the state as:

Successfully installed thin-1.6.1
1 gem installed

Since an error was encountered and a the file was rm -f'ed

<pre>
...
...
thin.c:338: warning: implicit declaration of function 'thin_http_parser_has_error'
rm -f thin_parser.so
</pre>

Even though something was amiss on our system, surely the install should fail?  Is ours just some edge, edge case?

This is true for 1.5.0 as well.

Full verbose output:

<pre>
gem install thin --verbose
GET http://rubygems.org/latest_specs.4.8.gz
302 Moved Temporarily
GET http://production.s3.rubygems.org/latest_specs.4.8.gz
200 OK
Installing gem thin-1.6.1
Downloading gem thin-1.6.1.gem
GET http://rubygems.org/gems/thin-1.6.1.gem
302 Moved Temporarily
GET http://bb-m.rubygems.org/gems/thin-1.6.1.gem
Fetching: thin-1.6.1.gem (100%)
200 OK
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/CHANGELOG
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/README.md
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/Rakefile
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/bin/thin
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/example/adapter.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/example/async_app.ru
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/example/async_chat.ru
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/example/async_tailer.ru
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/example/config.ru
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/example/monit_sockets
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/example/monit_unixsock
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/example/myapp.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/example/ramaze.ru
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/example/thin.god
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/example/thin_solaris_smf.erb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/example/thin_solaris_smf.readme.txt
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/example/vlad.rake
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/rack/adapter/loader.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/rack/adapter/rails.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/backends/base.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/backends/swiftiply_client.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/backends/tcp_server.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/backends/unix_server.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/command.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/connection.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/controllers/cluster.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/controllers/controller.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/controllers/service.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/controllers/service.sh.erb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/daemonizing.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/headers.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/logging.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/request.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/response.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/runner.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/server.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/stats.html.erb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/stats.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/statuses.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin/version.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/lib/thin.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/ext/thin_parser/ext_help.h
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/ext/thin_parser/parser.h
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/ext/thin_parser/parser.c
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/ext/thin_parser/thin.c
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/ext/thin_parser/extconf.rb
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/ext/thin_parser/common.rl
/opt/rh/ruby193/root/usr/share/gems/gems/thin-1.6.1/ext/thin_parser/parser.rl
Building native extensions.  This could take a while...
/opt/rh/ruby193/root/usr/bin/ruby extconf.rb
checking for main() in -lc... yes
creating Makefile
make
gcc -I. -I/opt/rh/ruby193/root/usr/include/x86_64-linux -I/opt/rh/ruby193/root/usr/include/ruby/backward -I/opt/rh/ruby193/root/usr/include -I.   -fPIC -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -mtune=generic -fPIC -m64 -o parser.o -c parser.c
gcc -I. -I/opt/rh/ruby193/root/usr/include/x86_64-linux -I/opt/rh/ruby193/root/usr/include/ruby/backward -I/opt/rh/ruby193/root/usr/include -I.   -fPIC -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -mtune=generic -fPIC -m64 -o thin.o -c thin.c
thin.c: In function 'Thin_HttpParser_alloc':
thin.c:242: warning: implicit declaration of function 'thin_http_parser_init'
thin.c: In function 'Thin_HttpParser_finish':
thin.c:294: warning: implicit declaration of function 'thin_http_parser_finish'
thin.c:296: warning: implicit declaration of function 'thin_http_parser_is_finished'
thin.c: In function 'Thin_HttpParser_execute':
thin.c:334: warning: implicit declaration of function 'thin_http_parser_execute'
thin.c:338: warning: implicit declaration of function 'thin_http_parser_has_error'
rm -f thin_parser.so
gcc -shared -o thin_parser.so parser.o thin.o -L. -L/opt/rh/ruby193/root/usr/lib64 -L. -rdynamic -Wl,-export-dynamic  -m64  -lruby -lc  -lpthread -lrt -ldl -lcrypt -lm   -lc
make install
/bin/mkdir -p /opt/rh/ruby193/root/usr/lib64/gems/exts/thin-1.6.1/lib
/usr/bin/install -c -m 0755 thin_parser.so /opt/rh/ruby193/root/usr/lib64/gems/exts/thin-1.6.1/lib
/opt/rh/ruby193/root/usr/share/gems/bin/thin
Successfully installed thin-1.6.1
1 gem installed
Installing ri documentation for thin-1.6.1...
rdoc --ri --op /opt/rh/ruby193/root/usr/share/gems/doc/thin-1.6.1/ri lib --title thin-1.6.1 Documentation
Parsing sources...
100% [22/22]  lib/thin.rb                                                       

Generating RI format into /opt/rh/ruby193/root/usr/share/gems/doc/thin-1.6.1/ri...

Files:       22

Classes:     30 (  5 undocumented)
Modules:     10 (  6 undocumented)
Constants:   55 ( 44 undocumented)
Attributes:  39 (  7 undocumented)
Methods:    202 (100 undocumented)

Total:      336 (162 undocumented)
 51.79% documented

Elapsed: 1.0s
Installing RDoc documentation for thin-1.6.1...
rdoc --op /opt/rh/ruby193/root/usr/share/gems/doc/thin-1.6.1/rdoc lib --title thin-1.6.1 Documentation
Parsing sources...
100% [22/22]  lib/thin.rb                                                       

Generating Darkfish format into /opt/rh/ruby193/root/usr/share/gems/doc/thin-1.6.1/rdoc...

Files:       22

Classes:     30 (  5 undocumented)
Modules:     10 (  6 undocumented)
Constants:   55 ( 44 undocumented)
Attributes:  39 (  7 undocumented)
Methods:    202 (100 undocumented)

Total:      336 (162 undocumented)
 51.79% documented

Elapsed: 1.8s
</pre>

**Comment by ashokmiryala** [comment]
use this it will resolve the problem
sudo gem install thin -- --with-cflags=\"-O2 -pipe -march=native -w\"
