### ISSUE TITLE
No way to disable SSLv2

### ISSUE THREAD

**Issue by ssamppa** [macournoyer/thin#214]
There should be a way to disable SSLv2 on Thin. SSLv2 is old and insecure nowadays and for example this https://www.ssllabs.com/ssltest/  will always give you F (failed) on the test.

**Comment by sodabrew** [comment]
EventMachine 1.2.0 now defaults to TLS (v1.0, v1.1, v1.2 if available in your OpenSSL version) and disables SSLv2 and SSLv3. Try updating the eventmachine gem and see if it meets your needs?

There are some extra configuration items that Thin may need to expose in the future.
