### ISSUE TITLE
Thin eating Signal traps with Eventmachine.

### ISSUE THREAD

**Issue by jaunkst** [macournoyer/thin#247]
Thin will complain about needing to stop the reactor, but a Signal.trap will never fire.

class App < Sinatra::Base
  #sinatra code
end

pid = fork do
  EM.run do
    Signal.trap("TERM") do
      puts "Terminating..."
      EM.stop()
    end
    EM.add_periodic_timer( 1 ) do 
      puts 'Still Running'
    end
    Thin::Server.start App, '0.0.0.0', 3000
  end
end

sleep 1
Process.kill("TERM", pid)

**Comment by sodabrew** [comment]
What versions of Ruby and EventMachine are you running?
