### ISSUE TITLE
Disable sendfile

### ISSUE THREAD

**Issue by balauru** [macournoyer/thin#259]
There is currently a issue with virtualbox and sendfiles, the requierment is to disable sendfile in your webserver. How can I do this in thin?

https://abitwiser.wordpress.com/2011/02/24/virtualbox-hates-sendfile/

**Comment by macournoyer** [comment]
This is likely added by Rails. Remove the Rack::Sendfile middleware.

**Comment by balauru** [comment]
Thanks,

**Comment by aaronholla** [comment]
How exactly would I go about removing the sendfile middleware? And would this affect anything in production if I remove this middleware?
