### ISSUE TITLE
Thin on Windows with Ruby 2.x leaking memory

### ISSUE THREAD

**Issue by neongrau** [macournoyer/thin#260]
As the EOL cycle for Ruby 1.9.3 approaches i'm in the process of upgrading to a newer Ruby version on Windows. Sadly right after starting thin the ruby process is starrting to tick up the memory in Ruby typical 16KB steps pretty much evry second.

I was able to reproduce this with Rails 3.2.21 and Rails 4.2 with Ruby 2.0.0 and 2.1.5 either 64bit and 32bit versions. Tested on Windows Server 2008 and 2012.

I'm suspecting either Thin or Eventmachine to be the culprit.

Happens on a plain vanilla Rails application created via. "rails new testapp" only thing i added to the gemfile was thin.

**Comment by neongrau** [comment]
After some further testing i've found that the memory leak that was ticking up the memory every second does not occur with Eventmachine 1.0.4 which was the oldest i could install under 2.1.5p273 [x64-mingw32]. Memory consumption is still considerably higher that what i was used from 1.9.3 but this could be normal as Ruby 2.1.x seems to have a much higher memory footprint.

**Comment by sodabrew** [comment]
EventMachine 1.0.5 and 1.0.6 had a memory leak issue. With EM 1.0.7 you should be good. Can you close this ticket if the issue is resolved?

**Comment by neongrau** [comment]
Sorry, forgot this. Yep that issue was solved with 1.0.7
Thanks again!
