### ISSUE TITLE
disable ssl3 via thin

### ISSUE THREAD

**Issue by cessien** [macournoyer/thin#273]
Is there support for disabling ssl3 in thin, using command line or configuration options?

**Comment by sodabrew** [comment]
EventMachine 1.2.0 now defaults to TLS (v1.0, v1.1, v1.2 if available in your OpenSSL version) and disables SSLv2 and SSLv3. Try updating the eventmachine gem and see if it meets your needs?

There are some extra configuration items that Thin may need to expose in the future.
