### ISSUE TITLE
How to set thin to silent mode?

### ISSUE THREAD

**Issue by ecnepsnai** [macournoyer/thin#277]
Hi, I want to silence all output from thin including this startup message:

> Thin web server (v1.6.3 codename Protein Powder)
> Maximum connections set to 1024
> Listening on localhost:8080, CTRL+C to stop

I see that in logging.rb there is a silent? function, but how do I get it to work?  I'm passing -q to rackup right now.

**Comment by macournoyer** [comment]
`thin -q ...`

`rackup` will no pass the option to thin.
