### ISSUE TITLE
Does Thin use the adapter that ships with Rack?

### ISSUE THREAD

**Issue by tenderlove** [macournoyer/thin#283]
Hi,

Sorry for posting a question in the Issues section.  Does Thin [actually use the adapter that Rack provides](https://github.com/rack/rack/blob/master/lib/rack/handler/thin.rb)?  My cursory testing says that it does not, but I wanted to check with you to make sure before I rm it.

Thank you!

**Comment by macournoyer** [comment]
Hey!

No, Thin doesn't use it internally. However the handler is used by `rails server` and `rackup -s thin` AFAIK.

I don't mind moving the handler to Thin if you do remove it.

**Comment by tenderlove** [comment]
Ah, I see.  Yes, I'd prefer to move it to Thin.  I'll send a PR!  Thank you.
