### ISSUE TITLE
no unix-domain acceptor 

### ISSUE THREAD

**Issue by zingbats** [macournoyer/thin#285]
I'm trying to use thin with rails 4.2 behind nginx. I have nginx configured to listen on several sockets, and thin configured to start them, but I keep getting this error when thin starts. 
I've checked paths, permissions on parent folders, etc. 
`start_unix_server': no unix-domain acceptor (RuntimeError)

Relevant configs are here: nginx vhost: 
https://github.com/LoveItLabs/PublicDocker/blob/master/rails4app/nginx.vhost

supervisord which starts thin:
https://github.com/LoveItLabs/PublicDocker/blob/master/rails4app/supervisord.conf#L7

Can I have a hint as to what this error means?

**Comment by macournoyer** [comment]
It's probably because the unix socket file already exist. Are you sure that process_num is expended to 0-4 in superversord?
