### ISSUE TITLE
thin doesn't remove pidfile if shut down cleanly

### ISSUE THREAD

**Issue by mfischer-zd** [macournoyer/thin#288]
When thin is terminated in a way it can catch (SIGTERM, SIGINT, etc.), it should remove its pidfile.

**Comment by macournoyer** [comment]
It should works. Any repro steps?

**Comment by mfischer-zd** [comment]
Where's the code to make it do it?

**Comment by macournoyer** [comment]
https://github.com/macournoyer/thin/blob/master/lib/thin/daemonizing.rb#L60

**Comment by mfischer-zd** [comment]
My mistake - this was based on a report from my colleagues, and I missed this bit of the code. Apologies for the disturbance!
