### ISSUE TITLE
SSL certificate / HTTPS issue using Thin rack ruby server

### ISSUE THREAD

**Issue by solyaris** [macournoyer/thin#290]
I have some troubles using Thin rack Ruby server (https://github.com/macournoyer/thin) to receice HTTPS webhooks. 

Maybe that's not exactly a problem related specifically to Thin but to SSL certificates configuration. 

I'd like to manage incoming HTTPS connections (webhooks: Telegram.org server call my Thin (sinatra/rack) app, sending messages updates through webhooks) 

Step 1. I created a SSL KEY and PEM files self-signed certificate, as described here: https://core.telegram.org/bots/self-signed

    openssl req -newkey rsa:2048 -sha256 -nodes -keyout YOURPRIVATE.key -x509 -days 365 -out 
    YOURPUBLIC.pem -subj "/C=US/ST=New York/L=Brooklyn/O=Example Brooklyn Company/CN=YOURDOMAIN.EXAMPLE"

Step 2. I call Telegram Server Bot API to receive webhooks at a specified HTTPS host/path, as described here: https://core.telegram.org/bots/api#setwebhook
API endpoint return success. 

Step 3. I run Thin with these parameters:

    bundle exec thin start --ssl --ssl-key-file ~/.ssl/YOURPRIVATE.key --ssl-cert-file ~/.ssl/YOURPUBLIC.pem --rackup /myhome/handyBOTS/rackup/handler.ru --address xxx.xxx.xxx.xxx      --port 8443  --environment production
    Thin web server (v1.6.4 codename Gob Bluth)
    ...
    ...
    ...

I have troubles in runt-time: 
I see Telegram remote server call the Thin sever webhooks, but Thin complain with laconic:

    <SSL_incomp><SSL_incomp><SSL_incomp><SSL_incomp><SSL_incomp><SSL_incomp><SSL_incomp><SSL_incomp><SSL_incomp><SSL_incomp><SSL_incomp><SSL_incomp><SSL_incomp><SSL_incomp>

So I'm confident that Thin server receives calls from remote Telegram Server but it doesn't process requestes. 
I presume that's some SSL configuration incongruence. 

Any idea ?

My specific question is:

**Which is the CRT file format Thin expects ?** 

It's correct to pass to Thin the PEM file with this command line parameter `--ssl-cert-file ~/.ssl/YOURPUBLIC.pem`  ?

Thanks

giorgio

**Comment by solyaris** [comment]
tryied to explain better the problem

**Comment by macournoyer** [comment]
You're likely missing a cert in the bundle. See https://github.com/eventmachine/eventmachine/issues/115

**Comment by solyaris** [comment]
Hi Marc, just to thank you and feed back: 
Yes, you was right to close the issue. Sorry. It was my fault on building up certificate. 

Honestly I no more tested thin SSL configuration (I have to), 
because I decided that's better to leave SSL /firewall/proxy work to NGINX, using Thin instance(s) as worker(s) behind. 

I feel you maybe agree, having read your old (2008), but still valid trick! about how to connect multiple thin instances to NGINX via unix sockets:
https://github.com/solyaris/BOTServer/blob/master/wiki/nginx.md#one-nginx--many-thin-workers-
https://github.com/solyaris/BOTServer#thanks-to

respect
giorgio

**Comment by macournoyer** [comment]
Thanks the update giorgio! Glad you worked it out
