### ISSUE TITLE
Compatibility with ActionCable

### ISSUE THREAD

**Issue by Nekromancer** [macournoyer/thin#298]
ActionCable from rails 5 is not working on thin. Whole problem is investigated and described here https://github.com/rails/rails/issues/23696 . My question is - is there possibility for Thin to enable rack hijack support?

**Comment by macournoyer** [comment]
It is possible, but I don't think it make sense to implement the Rack hijack API in Thin. The whole concept is based on blocking socket I/O and Thin uses non-blocking I/O.

So I would recommend you use another server is you need Rack hijack support.

The way to do it w/ Thin would be to use https://github.com/macournoyer/thin_async.

**Comment by macournoyer** [comment]
I just tested this out, and ActionCable does work w/ Thin!

w/ a few extra configs:

In your `Gemfile`:
```ruby
gem 'faye-websocket'
gem 'thin'
```

Create a `config/initializers/thin_action_cable.rb`:
```ruby
Rails.application.config.action_cable.use_faye = true
Faye::WebSocket.load_adapter 'thin'
```

**Comment by malonehedges** [comment]
@macournoyer My app is crashing when `Rails.application.config.action_cable.use_faye = true` is included but runs just fine with only `Faye::WebSocket.load_adapter 'thin'`. Is the first line required? I couldn't find any documentation on it anywhere but these GitHub issues.

**Comment by macournoyer** [comment]
@malonehedges what is the error message? Maybe you forgot to add the `gem 'faye-websocket'`

**Comment by malonehedges** [comment]
@macournoyer 

```
=> Booting Thin
=> Rails 5.1.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
/Users/malonehedges/.rvm/gems/ruby-2.4.1/gems/actioncable-5.1.1/lib/action_cable/engine.rb:37:in `block (3 levels) in <class:Engine>': undefined method `use_faye=' for #<ActionCable::Server::Configuration:0x007fe2bd4fa9a0> (NoMethodError)
```

**Comment by Llermy** [comment]
@macournoyer I actually have the same error as @malonehedges . In rails 5.0 everything works right, but in rails 5.1 I have the same error `undefined method 'use_faye=' for #<ActionCable::Server::Configuration:0x007fe2bd4fa9a0> (NoMethodError)`

I've checked `ActionCable::Server::Configuration` and the property `#use_faye` indeed doesn't exist any more for actioncable 5.1.
[ActionCable::Server::Configuration 5.0](http://www.rubydoc.info/gems/actioncable/5.0.1/ActionCable/Server/Configuration)
[ActionCable::Server::Configuration 5.1](http://www.rubydoc.info/gems/actioncable/5.1.0/ActionCable/Server/Configuration)
