### ISSUE TITLE
if a number of servers is set, thin starts as daemon

### ISSUE THREAD

**Issue by ChristianHirsch** [macournoyer/thin#301]
... even if daemonize is set to false in a config file. Is there a special reason for that?

**Comment by acrolink** [comment]
same here..

**Comment by aars** [comment]
https://github.com/macournoyer/thin/blob/a7d1174f47a4491a15b505407c0501cdc8d8d12c/lib/thin/controllers/cluster.rb#L23

Each server needs a pid.
