### ISSUE TITLE
Rack 2 support?

### ISSUE THREAD

**Issue by connorshea** [macournoyer/thin#302]
Rack 2 will be required for Rails 5, are there any plans to support Rack 2 in the Thin web server? Would be very nice to have.

**Comment by macournoyer** [comment]
Rack 2 is still in alpha. Once it's released, I plan to support it.

**Comment by connorshea** [comment]
I'm not sure if you'd prefer a full release, but I figured I'd mention that RC1 was just released today: https://github.com/rack/rack/releases/tag/2.0.0.rc1

**Comment by macournoyer** [comment]
Thanks for the heads up! Will look into it.

**Comment by macournoyer** [comment]
It seems Thin "just works" w/ Rack 2!

**Comment by connorshea** [comment]
Awesome :D Thanks!
