### ISSUE TITLE
do you guys think website font is little bit crazy?

### ISSUE THREAD

**Issue by 1c7** [macournoyer/thin#314]
![image](https://cloud.githubusercontent.com/assets/1804755/15627466/9c1963a4-2517-11e6-92d4-eb39f6d37512.png)
(above snapshot environment: chrome & win 10)
<br/><br/>
I mean...really? the font and width of main content is too small. my eyes hurt  
 is that a pun joke for "Thin"??

**Comment by remiprev** [comment]
> is that a pun joke for "Thin"??

I think so.
