### ISSUE TITLE
Can't get SSL to work on Windows

### ISSUE THREAD

**Issue by AaronMertes** [macournoyer/thin#315]
I used Thin in development of a rest api using Grape. I have had nothing but good experiences with Thin. However, the requirement in production is to use SSL and I cannot get this work. I've found some of the same complaints through searching, the solutions I've found don't seem to make a difference. I have downloaded OpenSSL and done what's described in the following post;

https://github.com/eventmachine/eventmachine/wiki/Building-EventMachine-with-SSL-on-Windows

But there is still no change in the error message about encryption not available on this event machine.

Is there any other posts or support one can direct me to get this working? I'd like to not have to introduce IIS in front of thin, but I've found that as another possibility.

**Comment by tobias-brunner** [comment]
I was able to get Thin to run in SSL mode on Windows by following these steps:

1. Download the developer package (32bit!) from http://slproweb.com/products/Win32OpenSSL.html
2. install into D:\OpenSSL-Win32
3. gem uninstall eventmachine => uninstall all versions
4. gem install eventmachine -v 1.2.0.1 --platform ruby -- --with-ssl-dir=D:\OpenSSL-Win32
5. set "config.force_ssl = true" in your environment.rb
6. thin start -e test --ssl -p 443 --ssl-key-file D:\....key --ssl-cert-file D:\....crt

but as of now, multiple parallel ajaxcalls don't work in my environment...
