### ISSUE TITLE
I get EventMachine::FileNotFoundException -- Letsencrypt SSL & Thin

### ISSUE THREAD

**Issue by acrolink** [macournoyer/thin#316]
The certificate and key files are in the specified location but I get the above mentioned error, like this:

```
/home/???/.rvm/gems/ruby-2.3.1/gems/eventmachine-1.2.0.1/lib/em/connection.rb:430:in `block in start_tls': Could not find /etc/letsencrypt/live/my_domain.net/privkey.pem for start_tls (EventMachine::FileNotFoundException)
```
Any idea what might be causing this? Thanks.

**Comment by tmm1** [comment]
File permissions perhaps?

**Comment by acrolink** [comment]
Indeed, I copied the key & cert files out of the Letsencrypt directory to my Rails app folder and problem solved. I guess I need to define a common group for the Letsencrypt directories and the Linux user running Thin/Rails to overcome the original issue. Meanwhile, a strange thing happens after SSL is running. When I visit my app from Chrome a pop up appears asking me to select a local certificate from my PC in order to communicate with my remote Rails app. Strange.. Never seen such a thing before.

**Comment by acrolink** [comment]
Solved by making some ownership/group/permission modifications.
