### ISSUE TITLE
Support for Transfer-Encoding: Chunked requests

### ISSUE THREAD

**Issue by thom-nic** [macournoyer/thin#323]
Clients who send requests to Thin a `Transfer-Encoding: chunked` request body are not handled correctly, probably because Thin is looking for a Content-Length header which will not be present when using chunked transfer encoding.  Thin appears to handle the request but only reads the first packet of data (the whole request body is not received) hence it's not possible to use rack middleware to parse the chunked request body.

This was originally reported in #71.  Note [Transfer-Encoding is part of the HTTP 1.1 spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.6).

Webrick, Puma, Passenger and the Unicorn family of servers all appear to support chunked transfer encoding.  

In my particular use case, I have IoT like devices with limited buffer size to construct a JSON POST body.  By using Chunked transfer coding, the entire request body does not need to be held in memory (and it's not necessary to calculate a `Content-Length` header) prior to initiating the request.  Instead the request is streamed and written to the TCP socket in pieces which I believe was the intent behind this feature of HTTP 1.1.

**Comment by timolehto** [comment]
Sad 😢
