### ISSUE TITLE
--max-conns won't let me start thin (fails while loading thin/connection)

### ISSUE THREAD

**Issue by ccoenen** [macournoyer/thin#336]
I am trying to write a tiny example with thin. It requires a maximum amount of connections (say, 10). For some reason thin crashes when I try to specify it via `--max-conns 10`. Thin is in my bundle and it can start just fine if i just do a `thin start`.

Thin *is* in my bundle, so it's probably not #115. The behaviour looks similar, though (LoadError for thin/connection).

<details>
<summary>bundle install output</summary>
<pre>
user@ubuntudev:~/workspace/test$ bundle install
Resolving dependencies...
Using hitimes 1.2.4
Using daemons 1.2.4
Using eventmachine 1.2.3
Using httpclient 2.8.3
Using rack 1.6.5
Using tilt 2.0.7
Using bundler 1.14.6
Using timers 4.1.2
Using rack-protection 1.5.3
Using thin 1.6.3
Using celluloid-essentials 0.20.5
Using celluloid-extras 0.20.5
Using celluloid-fsm 0.20.5
Using celluloid-pool 0.20.5
Using celluloid-supervision 0.20.6
Using sinatra 1.4.8
Using celluloid 0.17.3
Bundle complete! 4 Gemfile dependencies, 17 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
</pre>
</details>

<details>
<summary>Regular run with just thin start</summary>
<pre>
user@ubuntudev:~/workspace/test$ thin start
/home/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thin-1.7.0/lib/thin/server.rb:107: warning: constant ::Fixnum is deprecated
Using rack adapter
Thin web server (v1.7.0 codename Dunder Mifflin)
Maximum connections set to 1024
Listening on 0.0.0.0:3000, CTRL+C to stop
^C
Stopping ...
</pre>
</details>

<details>
<summary>behaviour with --max-conns 10</summary>
<pre>
user@ubuntudev:~/workspace/test$ thin start --max-conns 10
/home/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thin-1.7.0/lib/thin/server.rb:107: warning: constant ::Fixnum is deprecated
Using rack adapter
Thin web server (v1.7.0 codename Dunder Mifflin)
Maximum connections set to 10
Listening on 0.0.0.0:3000, CTRL+C to stop
/home/user/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require': cannot load such file -- thin/connection (LoadError)
        from /home/user/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from /home/user/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /home/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thin-1.7.0/lib/thin/backends/tcp_server.rb:16:in `connect'
        from /home/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thin-1.7.0/lib/thin/backends/base.rb:63:in `block in start'
        from /home/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run_machine'
        from /home/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run'
        from /home/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thin-1.7.0/lib/thin/backends/base.rb:73:in `start'
        from /home/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thin-1.7.0/lib/thin/server.rb:162:in `start'
        from /home/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thin-1.7.0/lib/thin/controllers/controller.rb:87:in `start'
        from /home/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thin-1.7.0/lib/thin/runner.rb:200:in `run_command'
        from /home/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thin-1.7.0/lib/thin/runner.rb:156:in `run!'
        from /home/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thin-1.7.0/bin/thin:6:in `<top (required)>'
        from /home/user/.rbenv/versions/2.4.1/bin/thin:22:in `load'
        from /home/user/.rbenv/versions/2.4.1/bin/thin:22:in `<main>'
</pre>
</details>

<details>
<summary>Versions and stuff</summary>

## Environment

Bundler   1.14.6
Rubygems  2.6.11
Ruby      2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
Git       2.5.0
Platform  x86_64-linux

### Gemfile

<pre>source 'https://rubygems.org'

gem 'thin'
gem 'sinatra'
gem 'celluloid'
gem 'httpclient'
</pre>

### Gemfile.lock

<pre>GEM
  remote: https://rubygems.org/
  specs:
    celluloid (0.17.3)
      celluloid-essentials
      celluloid-extras
      celluloid-fsm
      celluloid-pool
      celluloid-supervision
      timers (>= 4.1.1)
    celluloid-essentials (0.20.5)
      timers (>= 4.1.1)
    celluloid-extras (0.20.5)
      timers (>= 4.1.1)
    celluloid-fsm (0.20.5)
      timers (>= 4.1.1)
    celluloid-pool (0.20.5)
      timers (>= 4.1.1)
    celluloid-supervision (0.20.6)
      timers (>= 4.1.1)
    daemons (1.2.4)
    eventmachine (1.2.3)
    hitimes (1.2.4)
    httpclient (2.8.3)
    rack (1.6.5)
    rack-protection (1.5.3)
      rack
    sinatra (1.4.8)
      rack (~> 1.5)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    thin (1.6.3)
      daemons (~> 1.0, >= 1.0.9)
      eventmachine (~> 1.0)
      rack (~> 1.0)
    tilt (2.0.7)
    timers (4.1.2)
      hitimes

PLATFORMS
  ruby

DEPENDENCIES
  celluloid
  httpclient
  sinatra
  thin

BUNDLED WITH
   1.14.6
</pre>
</details>

**Comment by MikeFlint** [comment]
There's some earlier chat (not sure on which issue, but it's somewhere in this project) that confirms that max-conns is actually a limit on number of i/o streams Thin will permit. Thin will use a number of file descriptors just to get going, and this is probably more than 10, so I think this explains why having a limit as low as 10 stops Thin from starting. 

I've tried a limit of 32 on a very low load system, and that was occasionally failing with only a few open connections, and I now use 128.
