### ISSUE TITLE
Co-maintainer?

### ISSUE THREAD

**Issue by junaruga** [macournoyer/thin#337]
Good day @macournoyer 
Thank you for developing and maintaining `thin` gem.
I think you may be busy.
However there are 82 issues, 12 PRs right now.
I wish you to consider adding co-maintainer newly, if you have enough time.

**Comment by macournoyer** [comment]
Hi @junaruga! Are you proposing yourself? 😄

**Comment by junaruga** [comment]
Hi @macournoyer .

Ah I did not intend it.
I wanted to suggest recruit people who are interested in being co-maintainer, in this issue page.
But I am happy to be co-maintainer :-)

Personally I want to improve `thin`'s development environment.
I sent PR to support RSpec3.

But I may not have a enough knowledge to fix bug and develop new feature right now.
So, if I will be a co-maintainer, I want to recruit one more people as co-maintainer here.

Anyway, I think adding co-maintainer new for `thin` is improving current situation.

**Comment by junaruga** [comment]
@macournoyer 

Right now I want to contribute for
- Supporting Rspec3
- Testing with latest Rubies ((2.0, 2.1 if possible), 2.2, 2.3, 2.4) with Travis CI.

It's useful for our development, isn't it?

Can you enable Travis CI for me?

**Comment by ioquatix** [comment]
All done.
