### ISSUE TITLE
`bundler: failed to load command: thin (/app/vendor/bundle/ruby/2.2.0/bin/thin)` on Heroku

### ISSUE THREAD

**Issue by arslanaly47** [macournoyer/thin#340]
Ruby: 2.2.7
Rails: 3.2.21

In my Gemfile, I have: `gem 'thin'`

Everything goes as expected on local, but when deployed to Heroku, it says:

> Using rack adapter
> bundler: failed to load command: thin (/app/vendor/bundle/ruby/2.2.0/bin/thin)
> Heroku::API::Errors::ErrorWithResponse: Expected(200) <=> Actual(400 Bad Request)

I have been working on this problem for the past 5 hours, but still unable to get any solution. Is it a compatibility issue?

**Comment by cesarmtz93** [comment]
did you manage to fix this?

**Comment by Deacychen257** [comment]
me too

**Comment by kinoshitama2023** [comment]
me too
