### ISSUE TITLE
Thin isssue

### ISSUE THREAD

**Issue by 7teen20nine** [macournoyer/thin#356]
thin               
Traceback (most recent call last):                 
        7: from /usr/local/bin/thin:23:in `<main>' 
        6: from /usr/local/bin/thin:23:in `load'   
        5: from /usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/bin/thin:5:in `<top (required)>'        
        4: from /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'          
        3: from /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'          
        2: from /usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin.rb:39:in `<top (required)>'    
        1: from /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'          
/usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file --
thin_parser (LoadError)

**Comment by ioquatix** [comment]
It looks like install issue/compile native extensions failed.
