### ISSUE TITLE
SERVER_PORT is incorrectly set to 80 when SSL is used on default port of 443

### ISSUE THREAD

**Issue by MikeFlint** [macournoyer/thin#357]
If starting Thin using SSL option listening on port 443, the SERVER_PORT value should be 443.
Instead the value is set to the non-SSL default of 80.

Example
**config.ru**
```ruby
require_relative 'server'
run Server.new
```
**server.rb**
```ruby
require 'rack'
class Server
  def call(env)
    server = env['HTTP_ORIGIN']
    port = env['SERVER_PORT']
    html = "<html><head/><body><form method='post' action='/'><input type='text' name='field'/><input type='submit'/></form></body></html>"
    [200, {"Content-Type" => "text/html"}, [html+"<br/>We are #{server} on #{port}"] ]
  end
end
```
thin start -p 443 --ssl
=> reports port 80 in SERVER_PORT (incorrectly)

thin start -p 832 --ssl
=> reports port 832 in SERVER_PORT (correctly)

This causes Rack::Protection::HttpOrigin to incorrectly trigger a 403/Forbidden response.

I think somewhere in thin_parser.c a default of 443 should be set instead of 80, based on the request scheme being used.

**Comment by daniellenzofficial** [comment]
same issue here on ubuntu 18.04/20.04 with all rubies 2.0 and greater

**Comment by erikt9** [comment]
I'm still getting this behavior despite the issue being closed?  Had to resort to making custom middleware that changes the `env['SERVER_PORT']`, but ideally you shouldn't have to jump through that hoop.  As stated in the initial post, it seems the `thin_parser` is setting this value incorrectly.  Did anyone ever find a better solution to this?

**Comment by ioquatix** [comment]
Feel free to submit a PR to fix this behaviour.
