### ISSUE TITLE
Can't start Thin Server using Ruby 2.6

### ISSUE THREAD

**Issue by jotamartos** [macournoyer/thin#362]
Hi, 

I'm trying to start a Thin server to deploy a Spree application on Windows but it's throwing the following error 

```
SPREE_INSTALLATION_DIRECTORY/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2-x64-mingw32/lib/thin/backends/tcp_server.rb:18:in `unpack_sockaddr_in': no implicit conversion of nil into String (TypeError)
```

The error is similar to the one reported here:

https://github.com/macournoyer/thin/issues/358

The command I'm using is:

```
"RUBY_PATH\ruby.exe" "SPREE_INSTALLATION_DIRECTORY\bin\thin" start -p 3001 -e production -c "SPREE_INSTALLATION_DIRECTORY" -a 127.0.0.1
```

I tried to use different versions of the Rack gem but got the same error.

My environment is the following one:

OS: Windows Server 2016
Ruby Version: 2.6.5
Rails version: 6.0.2.2
Rack version: 2.1.2

Is this gem supported for Ruby 2.6 and the specifications above? 

Thanks

**Comment by ioquatix** [comment]
It looks like it's trying to bind to a nil address. Sorry, this is not a support forum. I don't know why it's not working or if it should be supported. Let me know if you figure out the specific issue which is causing this problem.
