### ISSUE TITLE
Fix mac install errors or document in readme

### ISSUE THREAD

**Issue by grosser** [macournoyer/thin#370]
see https://stackoverflow.com/questions/63278694/thin-and-puma-fail-with-similar-issues-error-failed-to-build-gem-native-exten

`bundle config build.thin --with-cflags="-Wno-error=implicit-function-declaration"`

**Comment by ioquatix** [comment]
This is already fixed on master branch, can you confirm?

**Comment by grosser** [comment]
works! ... time for a release ? (maybe a patch-release on 1.7 too ?)
