### ISSUE TITLE
When the version 1.8.0 or 2.0.0 is released?

### ISSUE THREAD

**Issue by junaruga** [macournoyer/thin#376]
Hi maintainers and @ioquatix 

I see the new version "1.8.0" is set on [lib/thin/version.rb](https://github.com/macournoyer/thin/blob/master/lib/thin/version.rb) while the current thin latest 1.x version is 1.7.2 [1].
When will we release the version 1.8.0 or 2.0.0?
I want to use the thin supporting RSpec 3, as the RPM package is managed on Fedora, required to run the tests on RSpec3 [2].

Thanks.

[1] https://rubygems.org/gems/thin
[2] https://src.fedoraproject.org/rpms/rubygem-thin

**Comment by tagliala** [comment]
Hi, 

another reason to cut a new release is #372 (TL;DR: `thin` stable does not build on macOS with XCode 12)

**Comment by ioquatix** [comment]
We will cut 1.8.0 and it will be the last maintenance release pending patch releases, hopefully before the end of the year.

**Comment by ioquatix** [comment]
If you want to help, you need to check, is the current master stable and reasonable to release, are there any outstanding PRs that should be merged, and do we need to update release notes.

**Comment by junaruga** [comment]
Thanks! For the above thin RPM package in Fedora, we released the the current thin latest version 1.7.2's RPM package, applying some patch files to run the tests on RSpec 3.

**Comment by ioquatix** [comment]
I have released 1.8.0 please try it out and report back.

**Comment by krzysiek1507** [comment]
Hi @ioquatix. Could you please push a git tag for 1.8.0?

**Comment by ioquatix** [comment]
I pushed the v1.8.0 tag - sorry, it wasn't done automatically because the thin release process didn't seem to include it.

**Comment by krzysiek1507** [comment]
Thank you!
