### ISSUE TITLE
Consider new release for ruby 3.2 support

### ISSUE THREAD

**Issue by thesamesam** [macournoyer/thin#393]
Hi folks,

Is there any chance a new release could be cut containing 829c3aaa48efcd0c289d856f068f5d0fb16edaac (https://github.com/macournoyer/thin/pull/392) for ruby 3.2 support?

Thanks!

**Comment by ioquatix** [comment]
Yep we could do this.

**Comment by ioquatix** [comment]
Okay, v1.8.2 "Ruby Razor" (suggested by ChatGPT) is released.

**Comment by thesamesam** [comment]
Thanks @ioquatix! Could you push the git tag too please if possible?

**Comment by ioquatix** [comment]
Thanks for reminding me to push the tag. The release process of thin has a few manual steps. It's done now.

**Comment by thesamesam** [comment]
Thanks a bunch, really appreciated!
