### ISSUE TITLE
Uninitialized constant Thin::Server::Fixnum (NameError) with ruby-3.2.2

### ISSUE THREAD

**Issue by shubham-selldo** [macournoyer/thin#394]
### When server is initialized with ruby - 3.2.2

![image](https://user-images.githubusercontent.com/88022038/234865431-2055a30b-10d6-4966-a2ef-a184a6e91f26.png)

**Comment by ioquatix** [comment]
Are you using the latest version?

**Comment by shubham-selldo** [comment]
I checked in latest version this issue is fixed by updating the code in dev env, due to some reason mailcatcher that i installed has older version of thin.
