### ISSUE TITLE
Deprecated Faye Usage with Action Cable and Thin Web Server Alternatives

### ISSUE THREAD

**Issue by Gu7z** [macournoyer/thin#401]
### Issue Description

It appears that the usage of Faye as a mode for Action Cable has been deprecated or is no longer supported. This is in reference to the documentation found on the Thin project's README page (https://github.com/macournoyer/thin?tab=readme-ov-file#usage-with-rails-action-cable), which suggests using Faye for WebSocket communication when using Rails applications with Thin as the web server.

Given the evolution of Rails and its ecosystem, and considering the information provided in the Rails GitHub issue (https://github.com/rails/rails/issues/30775), it's clear that there's a need for updated guidance on implementing WebSocket communication in Rails applications that utilize Thin as their web server.

### Questions/Concerns

1. **Recommended Alternatives:** What are the current recommended alternatives for WebSocket communication in Rails applications that rely on Thin? Are there any specific gems or configurations that are now preferred?
2. **Documentation Update:** Will there be an update to the Thin project's README or any official Rails documentation to reflect these changes and provide clear guidance moving forward?

### Conclusion

The clarity on these points would greatly assist developers in navigating the evolving landscape of Rails application development, especially those utilizing the Thin web server for deployment. Your guidance and recommendations would be greatly appreciated.

Thank you for your attention.

@macournoyer

**Comment by ioquatix** [comment]
I don’t think there is any good alternative except for using a different server. Either that, or someone needs to do the work here to make it work again. In either case we can update the documentation to explain this.

**Comment by macournoyer** [comment]
@ioquatix is correct. That was the only option based on EventMachine IIRC. Remove it from the README in 3f375389d29deae252e03080b07a1f10aa60d957. Thanks @Gu7z !
