### ISSUE TITLE
Thin returns 0 even when not started all instances

### ISSUE THREAD

**Issue by lzap** [macournoyer/thin#93]
When thin does not start all the instances it still returns 0. Example:

Configuration:

---

pid: tmp/pids/thin.pid
address: 0.0.0.0
wait: 30
timeout: 30
port: 5000
max_conns: 1024
require: []

environment: production
max_persistent_conns: 512
servers: 3
daemonize: yes

Occupy one port:

nc -l 5001 &

Then:

thin start --config config.yml
echo $?
0

The only way is to use pgrep and count them. Would be nice if the parent process would be able to return non-zero when not all instances are up.

**Comment by xsuchy** [comment]
Was this resolved? Or closed by accident?

**Comment by ioquatix** [comment]
Since no one is maintaining this gem, I decided to close all issues. If the issue is still relevant, please reopen it and submit a PR. The plan is to do at least one final maintenance release and I've merged as many PRs as makes sense.
